version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432

    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./dbfiles:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "9090:8080"
  
  billingapp-backend:
    build:
      context: ./java
      args:
       - JAR_FILE=*.jar
       - DB_PASSWORD=qwerty
    container_name: billingapp-backend
    environment:
       - JAVA_OPTS=
          -Xmx256M
          -Xms256M
    depends_on:
      - postgres
    ports:
      - 8080:8080 

  billingapp-frontend:
    build:
      context: ./angular
    container_name: billingapp-frontend
    depends_on:
      - billingapp-backend
    ports:
      - 80:80